import { Plugin } from "@opencode/plugin";
import { mkdir, readFile, realpath, writeFile, rename } from "node:fs/promises";
import { join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { GithubOptions } from "./config.js";
import { setupRuntime } from "./runtime.js";
import type { CommandRunner } from "./executor.js";

const marker = "// Generated by OpenCode 2 automation. Do not edit.\n";
const localPath = ".opencode/plugins/automation-runtime/index.js";

export function workerPlugin(options: GithubOptions, directory: string) {
  return Plugin.define({ id: "automation.runtime", async setup(ctx) {
    if (await realpath(ctx.location.directory) !== await realpath(directory)) return;
    return setupRuntime(ctx, GithubOptions.parse(options));
  } });
}

// Location-scoped hooks must be loaded in the worktree, including for a local
// installation or an advanced state directory outside the owner's checkout.
export async function installWorkerPlugin(directory: string, options: GithubOptions, run: CommandRunner) {
  const file = join(directory, localPath);
  if (await run(directory, ["git", "ls-files", "--", localPath])) throw new Error("The bot runtime loader path is tracked by Git; choose another path for that project file");
  const old = await readFile(file, "utf8").catch(error => { if (error.code !== "ENOENT") throw error; return undefined; });
  if (old !== undefined && !old.startsWith(marker)) throw new Error("Refusing to overwrite a customized bot runtime loader");
  const content = `${marker}import { workerPlugin } from ${JSON.stringify(import.meta.url)};\nexport default workerPlugin(${JSON.stringify(options)}, ${JSON.stringify(directory)});\n`;
  const exclude = resolve(directory, await run(directory, ["git", "rev-parse", "--git-path", "info/exclude"]));
  const ignored = await readFile(exclude, "utf8").catch(error => { if (error.code !== "ENOENT") throw error; return ""; });
  const rule = "/.opencode/plugins/automation-runtime/";
  if (!ignored.split(/\r?\n/).includes(rule)) {
    await mkdir(join(exclude, ".."), { recursive: true });
    await writeFile(exclude, `${ignored}\n${rule}\n`);
  }
  if (old === content) return;
  await mkdir(join(file, ".."), { recursive: true });
  const temporary = `${file}.${randomUUID()}.tmp`;
  await writeFile(temporary, content);
  await rename(temporary, file);
}
